"use client";
import { useState } from "react";

type Props={course:{id:string;title:string;subject:string;description:string;published:boolean;lessons:{id:string;title:string;summary:string|null;content:string;videoUrl:string|null;published:boolean;position:number}[];liveClasses:{id:string;title:string;provider:string;joinUrl:string;scheduledAt:Date|string;durationMin:number}[]}};
export default function CourseManager({course}:Props){
 const [title,setTitle]=useState(''); const [content,setContent]=useState(''); const [summary,setSummary]=useState(''); const [videoUrl,setVideoUrl]=useState(''); const [liveTitle,setLiveTitle]=useState(''); const [provider,setProvider]=useState('zoom'); const [joinUrl,setJoinUrl]=useState(''); const [scheduledAt,setScheduledAt]=useState(''); const [published,setPublished]=useState(course.published); const [lessons,setLessons]=useState(course.lessons); const [live,setLive]=useState(course.liveClasses); const [status,setStatus]=useState('');
 async function addLesson(e:React.FormEvent){e.preventDefault();const r=await fetch(`/api/teaching/courses/${course.id}/lessons`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,summary,content,videoUrl})});const d=await r.json();if(!r.ok){setStatus(d.error||'Could not save lesson');return;}setLessons([...lessons,d.lesson]);setTitle('');setSummary('');setContent('');setVideoUrl('');setStatus('Lesson saved.');}
 async function addLive(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/teaching/live',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({courseId:course.id,title:liveTitle,provider,joinUrl,scheduledAt})});const d=await r.json();if(!r.ok){setStatus(d.error||'Could not schedule class');return;}setLive([...live,d.liveClass]);setLiveTitle('');setJoinUrl('');setScheduledAt('');setStatus('Live class scheduled.');}
 async function togglePublish(){const r=await fetch(`/api/teaching/courses/${course.id}/publish`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({published:!published})});if(r.ok)setPublished(!published);}
 return <div className="space-y-6"><div className="flex flex-col md:flex-row md:items-end md:justify-between gap-4"><div><p className="text-sm text-brand-300">Course manager</p><h1 className="text-3xl font-bold mt-1">{course.title}</h1><p className="text-slate-400 mt-2">{course.subject} · {course.description}</p></div><button onClick={togglePublish} className={`rounded-xl px-4 py-2.5 text-sm font-semibold ${published?'bg-emerald-500/15 text-emerald-300':'bg-brand-600 text-white'}`}>{published?'Published':'Publish course'}</button></div>
 <div className="grid gap-5 xl:grid-cols-2"><form onSubmit={addLesson} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5 space-y-3"><h2 className="font-semibold text-lg">Add lesson / teaching note</h2><input value={title} onChange={e=>setTitle(e.target.value)} required placeholder="Lesson title" className="w-full rounded-xl bg-black/20 border border-white/10 px-4 py-3 text-sm"/><input value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Short summary" className="w-full rounded-xl bg-black/20 border border-white/10 px-4 py-3 text-sm"/><textarea value={content} onChange={e=>setContent(e.target.value)} required rows={8} placeholder="Lecture notes, explanations, examples, revision material…" className="w-full rounded-xl bg-black/20 border border-white/10 px-4 py-3 text-sm"/><input value={videoUrl} onChange={e=>setVideoUrl(e.target.value)} placeholder="Optional YouTube/recording URL" className="w-full rounded-xl bg-black/20 border border-white/10 px-4 py-3 text-sm"/><button className="w-full rounded-xl bg-brand-600 py-3 text-sm font-semibold">Save lesson</button></form>
 <form onSubmit={addLive} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5 space-y-3"><h2 className="font-semibold text-lg">Schedule online class</h2><input value={liveTitle} onChange={e=>setLiveTitle(e.target.value)} required placeholder="Class title" className="w-full rounded-xl bg-black/20 border border-white/10 px-4 py-3 text-sm"/><select value={provider} onChange={e=>setProvider(e.target.value)} className="w-full rounded-xl bg-black/20 border border-white/10 px-4 py-3 text-sm"><option value="zoom">Zoom</option><option value="youtube">YouTube Live</option><option value="whatsapp">WhatsApp</option><option value="external">Other / external</option></select><input value={joinUrl} onChange={e=>setJoinUrl(e.target.value)} required placeholder="Join / watch URL" className="w-full rounded-xl bg-black/20 border border-white/10 px-4 py-3 text-sm"/><input type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)} required className="w-full rounded-xl bg-black/20 border border-white/10 px-4 py-3 text-sm"/><button className="w-full rounded-xl bg-brand-600 py-3 text-sm font-semibold">Schedule class</button></form></div>
 <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><h2 className="font-semibold">Lessons ({lessons.length})</h2><div className="mt-3 space-y-2">{lessons.map(l=><div key={l.id} className="rounded-xl border border-white/5 bg-black/20 p-3"><div className="font-medium">{l.position+1}. {l.title}</div><div className="mt-2 flex items-center justify-between gap-2"><div className="text-xs text-slate-500">{l.published?'Published to students':'Draft'}</div><button onClick={async()=>{const next=!l.published;const r=await fetch(`/api/teaching/courses/${course.id}/lessons/publish`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lessonId:l.id,published:next})});if(r.ok)setLessons(lessons.map(x=>x.id===l.id?{...x,published:next}:x));}} className="rounded-lg border border-white/10 px-2.5 py-1.5 text-xs">{l.published?'Unpublish':'Publish'}</button></div></div>)}</div></section><section className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><h2 className="font-semibold">Live classes ({live.length})</h2><div className="mt-3 space-y-2">{live.map(l=><div key={l.id} className="rounded-xl border border-white/5 bg-black/20 p-3"><div className="font-medium">{l.title}</div><div className="text-xs text-slate-500 mt-1">{l.provider} · {new Date(l.scheduledAt).toLocaleString()}</div></div>)}</div></section></div>{status&&<p className="text-sm text-slate-400">{status}</p>}</div>;
}
