"use client";

import { useMemo, useState } from "react";

type Lesson={id:string;title:string;summary:string|null;content:string;videoUrl:string|null};
type Live={id:string;title:string;provider:string;joinUrl:string;scheduledAt:string;durationMin:number;recordingUrl:string|null};
export default function CourseView({ course, enrolled, completed }: { course:{id:string;title:string;subject:string;description:string;instructor:{name:string|null};lessons:Lesson[];liveClasses:Live[]}; enrolled:boolean; completed:Set<string> }) {
  const [isEnrolled, setIsEnrolled] = useState(enrolled); const [done, setDone] = useState(completed); const [selected, setSelected] = useState(course.lessons[0]?.id); const lesson = useMemo(()=>course.lessons.find(l=>l.id===selected), [course.lessons, selected]);
  function youtubeId(url:string){ try{const u=new URL(url); if(u.hostname.includes('youtu.be'))return u.pathname.slice(1); if(u.hostname.includes('youtube.com'))return u.searchParams.get('v') || u.pathname.split('/').filter(Boolean).pop() || null; return null;}catch{return null;} }
  async function enroll(){ const r=await fetch('/api/learn/enroll',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({courseId:course.id})}); if(r.ok)setIsEnrolled(true); }
  async function toggle(id:string){ if(!isEnrolled)return; const next=!done.has(id); await fetch('/api/learn/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lessonId:id,completed:next})}); const copy=new Set(done); next?copy.add(id):copy.delete(id); setDone(copy); }
  return <div className="space-y-6"><div className="rounded-3xl border border-white/10 bg-gradient-to-br from-brand-600/15 to-slate-950 p-6"><div className="text-sm text-brand-300">{course.subject}</div><h1 className="text-3xl font-bold mt-1">{course.title}</h1><p className="text-slate-400 mt-2 max-w-3xl">{course.description}</p><div className="mt-4 text-xs text-slate-500">Instructor: {course.instructor.name || 'Instructor'}</div>{!isEnrolled&&<button onClick={enroll} className="mt-5 rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-semibold">Enroll for free</button>}</div>
    {course.liveClasses.length>0&&<section className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><h2 className="font-semibold text-lg">Live & recorded classes</h2><div className="mt-3 space-y-2">{course.liveClasses.map(c=><div key={c.id} className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 rounded-xl border border-white/5 bg-black/20 p-4"><div><div className="font-medium">{c.title}</div><div className="text-xs text-slate-500 mt-1">{c.provider} · {new Date(c.scheduledAt).toLocaleString()} · {c.durationMin} min</div></div><div className="flex gap-2">{c.recordingUrl&&<a href={c.recordingUrl} target="_blank" rel="noreferrer" className="rounded-lg border border-white/10 px-3 py-2 text-xs">Recording</a>}{isEnrolled?<a href={c.joinUrl} target="_blank" rel="noreferrer" className="rounded-lg bg-brand-600 px-3 py-2 text-xs font-semibold">Join</a>:<span className="rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-500">Enroll to join</span>}</div></div>)}</div></section>}
    <div className="grid gap-5 lg:grid-cols-[320px_1fr]"><aside className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><h2 className="font-semibold">Lessons</h2><div className="mt-3 space-y-2">{course.lessons.map(l=><button key={l.id} onClick={()=>setSelected(l.id)} className={`w-full rounded-xl border px-3 py-3 text-left ${selected===l.id?'border-brand-500/50 bg-brand-500/10':'border-white/5 bg-black/20'}`}><div className="flex items-start justify-between gap-2"><span className="text-sm">{l.title}</span><span className={`text-[10px] ${done.has(l.id)?'text-emerald-300':'text-slate-600'}`}>{done.has(l.id)?'Done':'○'}</span></div></button>)}</div></aside><section className="rounded-2xl border border-white/10 bg-white/[0.03] p-6 min-h-[360px]">{lesson?<><div className="text-xs text-brand-300">Lesson</div><h2 className="text-2xl font-bold mt-1">{lesson.title}</h2><p className="text-slate-400 mt-2">{lesson.summary}</p><div className="mt-6 whitespace-pre-wrap text-sm leading-7 text-slate-300">{lesson.content}</div>{lesson.videoUrl&&youtubeId(lesson.videoUrl)?<div className="mt-6 aspect-video overflow-hidden rounded-2xl border border-white/10 bg-black"><iframe title="Lesson video" src={`https://www.youtube-nocookie.com/embed/${youtubeId(lesson.videoUrl)}`} className="h-full w-full" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div>:lesson.videoUrl&&<a className="mt-6 inline-block rounded-xl border border-white/10 px-4 py-2.5 text-sm" href={lesson.videoUrl} target="_blank" rel="noreferrer">Watch lesson video ↗</a>}<div><button onClick={()=>toggle(lesson.id)} disabled={!isEnrolled} className="mt-5 rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-semibold disabled:opacity-40">{done.has(lesson.id)?'Mark incomplete':'Mark lesson complete'}</button></div></>:<p className="text-slate-500">Select a lesson to begin.</p>}</section></div>
  </div>;
}
