"use client";

import { useState } from "react";

type Course = { id: string; title: string; description: string; subject: string; published: boolean; _count: { lessons: number; enrollments: number; liveClasses: number } };

export default function TeachingStudio({ initialCourses, role }: { initialCourses: Course[]; role: string }) {
  const [courses, setCourses] = useState(initialCourses);
  const [title, setTitle] = useState(""); const [subject, setSubject] = useState(""); const [description, setDescription] = useState(""); const [status, setStatus] = useState("");
  async function createCourse(e: React.FormEvent) { e.preventDefault(); setStatus(""); const res = await fetch("/api/teaching/courses", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, subject, description }) }); const data = await res.json(); if (!res.ok) { setStatus(data.error || "Could not create course"); return; } setCourses([data.course, ...courses]); setTitle(""); setSubject(""); setDescription(""); setStatus("Course created."); }
  const teachingActions = [["✦", "AI lesson planner", "Draft a lesson outline from your teaching objective."], ["□", "Quiz builder", "Turn your lesson into revision questions."], ["◷", "Live class", "Schedule a session and give students one place to join."], ["▤", "Student insights", "Track participation, completion and submissions."]];
  return <div className="space-y-7">
    <section className="hero-surface rounded-[2rem] border border-white/10 p-6 sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow">Teaching Studio</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Teach with more context.</h1><p className="mt-3 max-w-2xl text-slate-300">Build courses, publish teaching notes, run live sessions and use AI to prepare material—while you remain in control of what students see.</p></div><span className="rounded-full border border-sky-400/15 bg-sky-400/[0.06] px-3 py-1.5 text-xs text-sky-200">Role: {role}</span></div></section>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{teachingActions.map(([icon,title,desc])=><div key={title} className="feature-card"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-500/10 text-brand-300">{icon}</div><div className="mt-4 font-semibold">{title}</div><p className="mt-1 text-sm leading-6 text-slate-400">{desc}</p></div>)}</div>
    <div className="grid gap-6 xl:grid-cols-[.9fr_1.1fr]">
      <form onSubmit={createCourse} className="glass-panel rounded-[1.7rem] p-5 sm:p-6"><p className="eyebrow">Create</p><h2 className="mt-1 text-xl font-bold">Start a course</h2><p className="mt-2 text-sm text-slate-500">Keep the first version private, then publish when the content is ready.</p><div className="mt-5 space-y-3"><input value={title} onChange={e=>setTitle(e.target.value)} required placeholder="Course title" className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm outline-none focus:border-brand-500"/><input value={subject} onChange={e=>setSubject(e.target.value)} required placeholder="Subject / unit" className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm outline-none focus:border-brand-500"/><textarea value={description} onChange={e=>setDescription(e.target.value)} required rows={5} placeholder="What should students understand by the end?" className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm outline-none focus:border-brand-500"/><button className="w-full rounded-xl bg-brand-600 py-3 text-sm font-semibold shadow-lg shadow-brand-950/20">Create course</button></div>{status&&<p className="mt-3 text-xs text-slate-400">{status}</p>}</form>
      <section className="glass-panel rounded-[1.7rem] p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Courses</p><h2 className="mt-1 text-xl font-bold">Your teaching spaces</h2></div><span className="rounded-full border border-white/10 px-3 py-1 text-xs text-slate-500">{courses.length} total</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{courses.map(c=><div key={c.id} className="rounded-2xl border border-white/5 bg-black/20 p-4"><div className="flex items-start justify-between gap-3"><div><div className="font-medium">{c.title}</div><div className="mt-1 text-xs text-slate-500">{c.subject}</div></div><span className={`rounded-full px-2 py-1 text-[10px] ${c.published?'bg-emerald-500/10 text-emerald-300':'bg-white/5 text-slate-400'}`}>{c.published?'Published':'Draft'}</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-xs text-slate-500"><span>{c._count.lessons} lessons</span><span>{c._count.enrollments} learners</span><span>{c._count.liveClasses} live</span></div><a href={`/dashboard/teaching/${c.id}`} className="mt-4 block rounded-lg border border-white/10 px-3 py-2 text-center text-xs hover:bg-white/5">Open course workspace →</a></div>)}{!courses.length&&<div className="sm:col-span-2 rounded-2xl border border-dashed border-white/10 p-6 text-sm text-slate-500">No courses yet. Create the first one and build the teaching workspace from there.</div>}</div></section>
    </div>
  </div>;
}
